const INITIAL_PRODUCTS = [
    {
        id: 1,
        nameRu: "Ментол кристаллический",
        nameUz: "Mentol kristall",
        nameEn: "Menthol crystals",
        category: "chemical",
        image: "https://i.ibb.co/Xxb7VKYD/0e9280e5ee617a76aa82d2a5388ffdca.webp",
        prices: { retail: 350000, wholesale: 300000 },
        minQty: 25,
        descriptionRu: "Фармацевтический ментол для косметических и фармацевтических применений.",
        descriptionUz: "Kosmetik va farmatsevtik qo'llanish uchun farmatsevtik mentol.",
        descriptionEn: "Pharmaceutical menthol for cosmetic and pharmaceutical applications.",
        status: "active"
    },
    {
        id: 2,
        nameRu: "Прокаин гидрохлорид (Новокаин)",
        nameUz: "Prokain gidroxlorid (Novokain)",
        nameEn: "Procaine hydrochloride (Novocaine)",
        category: "chemical",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 350000, wholesale: 300000 },
        minQty: 25,
        descriptionRu: "Местный анестетик для фармацевтического производства.",
        descriptionUz: "Farmatsevtika ishlab chiqarish uchun mahalliy anestetik.",
        descriptionEn: "Local anesthetic for pharmaceutical manufacturing.",
        status: "active"
    },
    {
        id: 3,
        nameRu: "Бензокаин (Анестезин)",
        nameUz: "Benzokain (Anestezin)",
        nameEn: "Benzocaine (Anesthesin)",
        category: "chemical",
        image: "",
        prices: { retail: 350000, wholesale: 300000 },
        minQty: 25,
        descriptionRu: "Местный анестетик для медицинских и косметических продуктов.",
        descriptionUz: "Tibbiy va kosmetik mahsulotlar uchun mahalliy anestetik.",
        descriptionEn: "Topical anesthetic for medical and cosmetic products.",
        status: "active"
    },
    {
        id: 4,
        nameRu: "Дифенгидрамин гидрохлорид (Димедрол)",
        nameUz: "Difengidramin gidroxlorid (Dimedrol)",
        nameEn: "Diphenhydramine hydrochloride (Dimedrol)",
        category: "chemical",
        image: "",
        prices: { retail: 625000, wholesale: 550000 },
        minQty: 25,
        descriptionRu: "Антигистаминное средство для фармацевтического производства.",
        descriptionUz: "Farmatsevtika ishlab chiqarish uchun antigistamin vosita.",
        descriptionEn: "Antihistamine for pharmaceutical manufacturing.",
        status: "active"
    },
    {
        id: 5,
        nameRu: "Диклофенак натрия",
        nameUz: "Diklofenak natriy",
        nameEn: "Diclofenac sodium",
        category: "chemical",
        image: "",
        prices: { retail: 450000, wholesale: 380000 },
        minQty: 25,
        descriptionRu: "Нестероидный противовоспалительный препарат (НПВП) для фармацевтического производства.",
        descriptionUz: "Farmatsevtika ishlab chiqarish uchun steroid bo'lmagan yallig'lanishga qarshi dori (NSAID).",
        descriptionEn: "Non-steroidal anti-inflammatory drug (NSAID) for pharmaceutical manufacturing.",
        status: "active"
    },
    {
        id: 6,
        nameRu: "Цитиколин натрия (Citicoline sodium)",
        nameUz: "Tsitikolin natriy",
        nameEn: "Citicoline sodium",
        category: "chemical",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 4000000, wholesale: 4000000 },
        minQty: 25,
        descriptionRu: "Ноотропный ингредиент для добавок для здоровья мозга.",
        descriptionUz: "Miya sog'ligi uchun qo'shimchalar uchun nootrop ingredient.",
        descriptionEn: "Nootropic ingredient for brain health supplements.",
        status: "active"
    },
    {
        id: 7,
        nameRu: "Симетикон эмульсия 30%",
        nameUz: "Simetikon emulsiya 30%",
        nameEn: "Simethicone emulsion 30%",
        category: "chemical",
        image: "",
        prices: { retail: 230000, wholesale: 230000 },
        minQty: 50,
        descriptionRu: "Антифлатулент для фармацевтических препаратов.",
        descriptionUz: "Farmatsevtik preparatlar uchun antiflatulent.",
        descriptionEn: "Antiflatulent for pharmaceutical preparations.",
        status: "active"
    },
    {
        id: 8,
        nameRu: "Повидон йод",
        nameUz: "Povidon yod",
        nameEn: "Povidone iodine",
        category: "chemical",
        image: "",
        prices: { retail: 450000, wholesale: 400000 },
        minQty: 25,
        descriptionRu: "Антисептик для фармацевтических и медицинских применений.",
        descriptionUz: "Farmatsevtik va tibbiy qo'llanishlar uchun antiseptik.",
        descriptionEn: "Antiseptic for pharmaceutical and medical applications.",
        status: "active"
    },
    {
        id: 9,
        nameRu: "Полиэтиленгликоль 6000 (ПЭГ 6000)",
        nameUz: "Polietilenglikol 6000 (PEG 6000)",
        nameEn: "Polyethylene glycol 6000 (PEG 6000)",
        category: "excipient",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 130000, wholesale: 100000 },
        minQty: 25,
        descriptionRu: "Фармацевтический эксципиент ПЭГ 6000.",
        descriptionUz: "Farmatsevtik eksipiyent PEG 6000.",
        descriptionEn: "Pharmaceutical excipient PEG 6000.",
        status: "active"
    },
    {
        id: 10,
        nameRu: "Магния стеарат",
        nameUz: "Magniy stearat",
        nameEn: "Magnesium stearate",
        category: "excipient",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 75000, wholesale: 75000 },
        minQty: 10,
        descriptionRu: "Смазывающий агент для производства таблеток.",
        descriptionUz: "Tablet ishlab chiqarish uchun yog'lovchi modda.",
        descriptionEn: "Lubricant for tablet manufacturing.",
        status: "active"
    },
    {
        id: 11,
        nameRu: "Метилпарабен (Нипагин)",
        nameUz: "Metilparaben (Nipagin)",
        nameEn: "Methylparaben (Nipagin)",
        category: "excipient",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 350000, wholesale: 300000 },
        minQty: 25,
        descriptionRu: "Консервант для косметических и фармацевтических продуктов.",
        descriptionUz: "Kosmetik va farmatsevtik mahsulotlar uchun konservant.",
        descriptionEn: "Preservative for cosmetic and pharmaceutical products.",
        status: "active"
    },
    {
        id: 12,
        nameRu: "Пропилпарабен (Нипазол)",
        nameUz: "Propilparaben (Nipazol)",
        nameEn: "Propylparaben (Nipazol)",
        category: "excipient",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 350000, wholesale: 300000 },
        minQty: 25,
        descriptionRu: "Консервант для косметических и фармацевтических продуктов.",
        descriptionUz: "Kosmetik va farmatsevtik mahsulotlar uchun konservant.",
        descriptionEn: "Preservative for cosmetic and pharmaceutical products.",
        status: "active"
    },
    {
        id: 13,
        nameRu: "Пропилпарабен натрий",
        nameUz: "Propilparaben natriy",
        nameEn: "Sodium propylparaben",
        category: "excipient",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 350000, wholesale: 300000 },
        minQty: 25,
        descriptionRu: "Консервант для косметических и фармацевтических продуктов.",
        descriptionUz: "Kosmetik va farmatsevtik mahsulotlar uchun konservant.",
        descriptionEn: "Preservative for cosmetic and pharmaceutical products.",
        status: "active"
    },
    {
        id: 14,
        nameRu: "Гидроксипропилметилцеллюлоза (Гипромелоза) HPMC",
        nameUz: "Gidroksipropilmetiltsellyuloza (Gipromeloza) HPMC",
        nameEn: "Hydroxypropyl methylcellulose (HPMC)",
        category: "excipient",
        image: "https://i.ibb.co/RGZXt7W7/16e5b0b663948251fb41b21e27bc7299.webp",
        prices: { retail: 250000, wholesale: 190000 },
        minQty: 25,
        descriptionRu: "Гипромеллоза для покрытия таблеток.",
        descriptionUz: "Tablet qoplamalari uchun gipromeloza.",
        descriptionEn: "Hydroxypropyl methylcellulose for tablet coating.",
        status: "active"
    },
    {
        id: 15,
        nameRu: "Коллоидный диоксид кремния (Аэросил 200)",
        nameUz: "Kolloidal kremniy dioksid (Aerosil 200)",
        nameEn: "Colloidal silicon dioxide (Aerosil 200)",
        category: "excipient",
        image: "",
        prices: { retail: 2200000, wholesale: 220000 },
        minQty: 10,
        descriptionRu: "Фармацевтический наполнитель для таблеток и капсул.",
        descriptionUz: "Tabletalar va kapsulalar uchun farmatsevtik to'ldirgich.",
        descriptionEn: "Pharmaceutical excipient for tablets and capsules.",
        status: "active"
    },
    {
        id: 16,
        nameRu: "Кроскармеллоза натрий",
        nameUz: "Kroskarmeloza natriy",
        nameEn: "Croscarmellose sodium",
        category: "excipient",
        image: "https://i.ibb.co/9mDLD7Cb/1ef3e382a9d3d4e76ddb914f6195f577.webp",
        prices: { retail: 300000, wholesale: 275000 },
        minQty: 25,
        descriptionRu: "Супердизинтегрант для фармацевтических таблеток.",
        descriptionUz: "Farmatsevtik tabletalar uchun superdisintegrant.",
        descriptionEn: "Superdisintegrant for pharmaceutical tablets.",
        status: "active"
    },
    {
        id: 17,
        nameRu: "Микрокристаллическая целлюлоза 101 (МКЦ 101)",
        nameUz: "Mikrokristallik tsellyuloza 101 (MKTS 101)",
        nameEn: "Microcrystalline cellulose 101 (MCC 101)",
        category: "excipient",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 75000, wholesale: 75000 },
        minQty: 20,
        descriptionRu: "Микрокристаллическая целлюлоза 101 для производства таблеток.",
        descriptionUz: "Tablet ishlab chiqarish uchun mikrokristallik tsellyuloza 101.",
        descriptionEn: "Microcrystalline cellulose 101 for tablet manufacturing.",
        status: "active"
    },
    {
        id: 18,
        nameRu: "Натрий карбоксиметилцеллюлоза (Натрий КМЦ)",
        nameUz: "Natriy karboksimetiltsellyuloza (Natriy KMTS)",
        nameEn: "Sodium carboxymethylcellulose (CMC)",
        category: "excipient",
        image: "",
        prices: { retail: 100000, wholesale: 100000 },
        minQty: 25,
        descriptionRu: "Натрий КМЦ для фармацевтических применений.",
        descriptionUz: "Farmatsevtik qo'llanishlar uchun natriy KMTS.",
        descriptionEn: "Sodium CMC for pharmaceutical applications.",
        status: "active"
    },
    {
        id: 19,
        nameRu: "Натрия крахмал гликолят",
        nameUz: "Natriy kraxmal glikolat",
        nameEn: "Sodium starch glycolate",
        category: "excipient",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 75000, wholesale: 75000 },
        minQty: 25,
        descriptionRu: "Супердизинтегрант для фармацевтических таблеток.",
        descriptionUz: "Farmatsevtik tabletalar uchun superdisintegrant.",
        descriptionEn: "Superdisintegrant for pharmaceutical tablets.",
        status: "active"
    },
    {
        id: 20,
        nameRu: "Хинолин жёлтый (Quinoline yellow)",
        nameUz: "Xinolin sariq (Quinoline yellow)",
        nameEn: "Quinoline yellow",
        category: "chemical",
        image: "",
        prices: { retail: 600000, wholesale: 600000 },
        minQty: 5,
        descriptionRu: "Пищевой краситель для фармацевтической и пищевой промышленности.",
        descriptionUz: "Farmatsevtika va oziq-ovqat sanoati uchun ozuqali bo'yoq.",
        descriptionEn: "Food colorant for pharmaceutical and food industry.",
        status: "active"
    },
    {
        id: 21,
        nameRu: "Солнечный закат (Sunset yellow)",
        nameUz: "Quyosh botishi sariq (Sunset yellow)",
        nameEn: "Sunset yellow",
        category: "chemical",
        image: "",
        prices: { retail: 600000, wholesale: 600000 },
        minQty: 5,
        descriptionRu: "Пищевой краситель для фармацевтической и пищевой промышленности.",
        descriptionUz: "Farmatsevtika va oziq-ovqat sanoati uchun ozuqali bo'yoq.",
        descriptionEn: "Food colorant for pharmaceutical and food industry.",
        status: "active"
    },
    {
        id: 22,
        nameRu: "Нитрофуразол (Фурацилин)",
        nameUz: "Nitrofurozol (Furatsilin)",
        nameEn: "Nitrofurazone (Furacilin)",
        category: "chemical",
        image: "https://i.ibb.co/xKRbQpNG/b121558f3199ed5ca38627299198147a.webp",
        prices: { retail: 1150000, wholesale: 1050000 },
        minQty: 25,
        descriptionRu: "Антисептик для наружного применения.",
        descriptionUz: "Tashqi qo'llanish uchun antiseptik.",
        descriptionEn: "Antiseptic for external use.",
        status: "active"
    },
    {
        id: 23,
        nameRu: "Фенирамина малеат",
        nameUz: "Feniramina maleat",
        nameEn: "Pheniramine maleate",
        category: "chemical",
        image: "https://i.ibb.co/N2JXcMXZ/4.webp",
        prices: { retail: 2600000, wholesale: 2400000 },
        minQty: 25,
        descriptionRu: "Антигистаминное средство для фармацевтического производства.",
        descriptionUz: "Farmatsevtika ishlab chiqarish uchun antigistamin vosita.",
        descriptionEn: "Antihistamine for pharmaceutical manufacturing.",
        status: "active"
    }
];

// Node.js uchun export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { INITIAL_PRODUCTS };
}